### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by yannikHoeflich**
My plan was to solve some issues. Some parts were very hard to find and many files are horrible long, partly through repetition of code.

I just started some refactoring, and much is still required to make the code more readable and better maintainable.

### CODE REVIEW

**Comment by bman46** [comment]
Thanks @yannikHoeflich for the PR. A cleanup has been needed for awhile and I appreciate you taking on the task! I'll review this over the next couple days.

**Comment by yannikHoeflich** [comment]
Don't expect to much though. I just started a little bit with the SlashCommands and some, what I believe, are artifacts of older c# versions

**Comment by bman46** [comment]
Reviewed code changes and they lgtm. Approved CodeQL runner and I will manually test before approving. Thanks again!

**Comment by bman46** [comment]
Tested for functionality successfully. If you could review the CodeQL suggestions that would be great!

**Comment by yannikHoeflich** [comment]
Sure, most suggestions should be solved. But some of the suggestions are because of the generic try catch. Meant by that is:

```csharp
try{
    // ...
} catch(Exception ex){
    // ...
}
```

In most cases you should catch specific Exceptions and continue the execution differently depending on the error. But in some cases, you just want to catch all, so I can not really do anything about the note.

**Comment by bman46** [comment]
> Sure, most suggestions should be solved. But some of the suggestions are because of the generic try catch. Meant by that is:
> 
> ```cs
> try{
>     // ...
> } catch(Exception ex){
>     // ...
> }
> ```
> 
> In most cases you should catch specific Exceptions and continue the execution differently depending on the error. But in some cases, you just want to catch all, so I can not really do anything about the note.

Yep, im fine just leaving them as is for now. Thanks!

**Review by bman46 — APPROVED** [review]
lgtm! I appreciate it!

**Pull request merged**
